##########################################################################
##########################################################################
hooks:
  all:
    pre:
      - type: oidc
        provider: aws
        role_arn: "arn:aws:iam::654654366125:role/terrateam-dev"